/// Flutter icons IRPooshesh
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IRPooshesh
///      fonts:
///       - asset: fonts/IRPooshesh.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class IRPooshesh {
  IRPooshesh._();

  static const _kFontFam = 'IRPooshesh';
  static const String? _kFontPkg = null;

  static const IconData menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_text = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_text_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_forward = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_text_2 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_normal = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_1 = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
